import type { Metadata } from "next";
import { MuseoModerno, Kalam, Londrina_Solid } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/header/header";

const museoModerno = MuseoModerno({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: '--font-museo-moderno'
});

const londrinaSolid = Londrina_Solid({
  subsets: ["latin"],
  weight: ["300", "400"],
  variable: '--font-londrina-solid'
});

const kalam = Kalam({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
  variable: '--font-kalam'
});

export const metadata: Metadata = {
  title: "Rachão",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={museoModerno.className}>
        <Header/>
        {children}
      </body>
    </html>
  );
}
