import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from 'sonner';
import { Header } from "@/components/header/header";
import { kalam, londrinaSolid, museoModerno } from "./fonts";
import { LoadingProvider } from "@/contexts/loading-context";

export const metadata: Metadata = {
  title: "Rachão",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" className={`${museoModerno.variable} ${londrinaSolid.variable} ${kalam.variable}`}>
      <LoadingProvider>
        <body className="font-museo text-black dark:text-white bg-background dark:bg-background-foreground">
          <Header/>
          {children}
          <Toaster richColors closeButton/>
        </body>
      </LoadingProvider>
    </html>
  );
}
