import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/components/header/header";
import { kalam, londrinaSolid, museoModerno } from "./fonts";

export const metadata: Metadata = {
  title: "Rachão",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" className={`${museoModerno.variable} ${londrinaSolid.variable} ${kalam.variable}`}>
      <body className="font-museo bg-zinc-100">
        <Header/>
        {children}
      </body>
    </html>
  );
}
