import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Meus Rachões",
  description: "Generated by create next app",
};

export default function MeusrachoesLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="p-20">
        {children}
    </div>
  );
}
